### ISSUE TITLE
Tabbed meta boxes

### ISSUE THREAD

**Issue by ghost** [No-Half-Pixels/Fluent-Framework#29]
**feature request

**Comment by leemason** [comment]
sneek peek at 1.0.6
![screen shot 2014-08-03 at 17 04 33](https://cloud.githubusercontent.com/assets/1238646/3791092/eb7c98cc-1b27-11e4-87be-9c9a969a5664.png)

**Comment by leemason** [comment]
don't forget to give the framework a nice rating on code canyon ;-)

**Comment by leemason** [comment]
added 1.0.6

**Comment by ghost** [comment]
Rated the plugins both as soon as I bought them, didn't need to install or test since I already know I am buying into quality. Thanks for adding this. Tabbed options page will be awesome if possible.
