### ISSUE TITLE
Image Select / Radio for NHP

### ISSUE THREAD

**Issue by ghost** [No-Half-Pixels/Fluent-Framework#31]
I would like to convert to use NHP from Redux, in the product I am building it makes use headily on Image select field. Please consider adding this so I can make the transition.

**Comment by leemason** [comment]
hello cmwwebfx,

sorry that field already exists, i forgot to update the docs with it.

here is the updated documentation for this field:

http://support.nohalfpixels.com/documentation/fluent-framework/#article-164

**Comment by ghost** [comment]
Thanks Lee for pointing me to that, will try start making my transition this weekend.
- Ciaran
