### ISSUE TITLE
Embedding framework

### ISSUE THREAD

**Issue by ghost** [No-Half-Pixels/Fluent-Framework#34]
Hi Lee,

Here is what I have added to my functions, and still does not show the framework options.

```
/**
 * Include Fluent Framework
 */
include_once( get_template_directory() . 'inc/fluent-framework/fluent-framework.php');
Fluent_Base::$url = 'inc/fluent-framework/example-usage.php';
```

I must be missing the plain obvious to get the theme options to show right away. Granted I am trying to do this without my developer being involved as he is away for a week. Just trying to figure this part out myself.

Sorry, just to avoid confusion I am looking to embed only in order to make the complete switch from Redux to Fluent.

**Comment by leemason** [comment]
hello cmwwebfx,

thats a little wrong, but not to worry, if you want to see the sample data this is what you need to do:
1. include the framework (done)
2. define FLUENT_DEMO*
3. set the base url (done but not quite right**) 
- you can do this in the wp-config.php or just before you include the framework:

``` php
if(!defined('FLUENT_DEMO')){
define('FLUENT_DEMO', true);
}
```

*\* i think your a little confused here, we will try to be more specific in the next version of the docs. the fluent base url is the path to the framework folder as a url, not to include the example usage, so in themes this would be:

``` php
Fluent_Base::$url = get_template_directory_uri() . 'inc/fluent-framework/';
```

we set this if the framework is not being used a plugin so it has a base url to load all the assets from.

**Comment by ghost** [comment]
Hi Lee, I am not sure why I would need to define the Fluent_Demo? I have not setup multisite install of the fluent demo yet. I will do that another time on the demo site.

**Comment by leemason** [comment]
ahh, thats confusing isn't it, we need to look at that.

FLUENT_DEMO defines if you want to view the demo usage of the fluent framework. its not in any way associated with the fluent demo plugin (need to sort that out).

alternatively you can just include the fluent-framework/example-usage.php file after including the framework file.

**Comment by ghost** [comment]
However I have given it another shot, and finally got it... sort of
The dashboard is not happy with the support widget, the icon spinner is going round and round plenty though.

Now it is embedded I can start playing.

FYI, I have loaded up from my function file my extras.php in the inc folder, and in the extras I have placed this, and please advise if it still looks a bit iffy.

```
/**
 * Include Fluent Framework
 */
include_once( dirname( __FILE__ ) . '/fluent-framework/fluent-framework.php');
Fluent_Base::$url = get_template_directory_uri() . '/fluent-framework/';
include_once( dirname( __FILE__ ) . '/fluent-framework/example-usage.php');
```

**Comment by leemason** [comment]
the spinner suggests the assets still aren't being loaded.

is the fluent-framework folder inside the inc folder?

if so the base url should be:

``` php
Fluent_Base::$url = get_template_directory_uri() . '/inc/fluent-framework/';
```

**Comment by ghost** [comment]
Perfect, that sorted it 100%. Thanks Lee, I will include this in my fiveminutewp movie for others. This is something on a side project making short flicks of subjects. So I will like to do a series of Youtube movies most likely of Fluent. Sort of do it in small 4-5 minute chunks. ideal for those sitting on a bus wanting to learn something.

**Comment by leemason** [comment]
that sounds great, let me know when you do it, I'm gathering (and making) press about the framework to put into a section about it soon.

**Comment by ghost** [comment]
So far so good Lee. Your help has been a real blessing. We have Fluent converted over mostly in the plugin so far. Thank you.
