### ISSUE TITLE
Background field missing

### ISSUE THREAD

**Issue by ghost** [No-Half-Pixels/Fluent-Framework#35]
Lee, a big part of our plugin is using a background field. However we have started the process of making the switch from Redux to Fluent, and have hit a point that is a possible big issue. Is this something that is coming soon? 

Here is what we have at the moment using redux in a metabox, and need to be doing the same with Fluent Framework.

![background options](https://cloud.githubusercontent.com/assets/1312880/3811230/67083292-1c9c-11e4-800a-c12c4dbb5dce.jpg)

**Comment by leemason** [comment]
ill get this one added as soon as i can.

**Comment by leemason** [comment]
Added 1.0.7
