### ISSUE TITLE
need clarification in creating metabox

### ISSUE THREAD

**Issue by premiumsupport365** [No-Half-Pixels/Fluent-Framework#38]
Hello lee
I have tried to create metabox by following the documentation and I couldnt bring it using the following code
$instance = new Fluent_Options_Page($args, $sections);

but when I looked in to the example code and i saw a line with Fluent_Store::set('metaboxes'

then I tried by the following method and it worked
Fluent_Store::set('metaboxes', new Fluent_Options_Meta( $args, $sections));

but in documentation it is not mentioned. can you clarify about this issue.

thanks for your good work mate.
cheers

**Comment by leemason** [comment]
you don't have to store it, i think what your misunderstanding is in the top example you are using the options page class, you need to use the metabox class:

``` php
new Fluent_Options_Meta( $args, $sections);
```

the store class is currently being documented  and its uses will become clear in future updates. (currently it is only used internally for the support form option).
