### ISSUE TITLE
UI is not clear for multiple select field

### ISSUE THREAD

**Issue by premiumsupport365** [No-Half-Pixels/Fluent-Framework#39]
![select field](https://cloud.githubusercontent.com/assets/1852778/3812573/913d9e44-1cab-11e4-9a8b-0d3de3cc41d8.png)

I have assigned a multiple field and noted that the only way to delete the selected field is hit delete button. I hope the select2 javascript framework provides a delete icon to deselect the fields. which is missing here. I am not sure what method you implemented for select field.

hope there could be a upcoming solution for this.
Thanks Mate

**Comment by leemason** [comment]
by default it is like it is, however there is a plugin for selective which adds a cross to the items, ill try and get that added in the next release.

**Comment by leemason** [comment]
Added crosses in 1.0.7
