### ISSUE TITLE
is compiler action available

### ISSUE THREAD

**Issue by premiumsupport365** [No-Half-Pixels/Fluent-Framework#40]
Hello lee

need to know whether we have compiler action available like in redux, where we can interpret and save the data when it is altered. I would like to capture the option and store it in a separate file.
does that make sense ?
can you guide on this one mate.

**Comment by leemason** [comment]
there isn't but will be a compiler in a near release.

however it sounds like you want to save a physical file?

you can do this using the `fluent/options/page/$option_name/save` filter.

this gets passed the $new and $old values during the options save, so you could hook into this and save your physical file like that.

**Comment by leemason** [comment]
This is detailed here: https://github.com/No-Half-Pixels/Fluent-Framework/issues/19
